# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ThoroughbredInsider' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ThoroughbredInsider
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxRealm'
  pod 'NSObject+Rx'
  pod 'RxAlamofire'
  pod 'RxPager', :git => 'https://github.com/N1k1tung/RxPager.git'
  pod 'AlamofireImage'
  pod 'RealmSwift'
  pod 'SwiftyJSON'
  pod 'IQKeyboardManagerSwift'
  pod 'KeychainAccess'

end

target 'UIComponents' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UIComponents

end
